using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace AStar.Dev.Source.Generators.Generators.StronglyTypedId;

internal static class StronglyTypedIdEmitter
{
    internal static void Emit(SourceProductionContext context, StronglyTypedIdModel model)
    {
        var source = BuildSource(model);
        context.AddSource(
            hintName: $"{model.Namespace}.{model.StructName}.g.cs",
            sourceText: SourceText.From(source, Encoding.UTF8));
    }

    private static string BuildSource(StronglyTypedIdModel m)
    {
        var sb = new StringBuilder();

        _ = sb.AppendLine("// <auto-generated/>");
        _ = sb.AppendLine("#nullable enable");
        _ = sb.AppendLine();
        _ = sb.AppendLine("using System;");
        _ = sb.AppendLine("using System.Text.Json;");
        _ = sb.AppendLine("using System.Text.Json.Serialization;");
        _ = sb.AppendLine();
        _ = sb.AppendLine($"namespace {m.Namespace};");
        _ = sb.AppendLine();

        // ── Struct declaration ──────────────────────────────────────────────
        _ = sb.AppendLine($"[JsonConverter(typeof({m.StructName}.{m.StructName}JsonConverter))]");
        _ = sb.AppendLine($"public readonly partial record struct {m.StructName} :");
        _ = sb.AppendLine($"    global::System.IComparable<{m.StructName}>,");
        _ = sb.AppendLine($"    global::System.IParsable<{m.StructName}>");
        _ = sb.AppendLine("{");

        // ── Backing value ───────────────────────────────────────────────────
        _ = sb.AppendLine($"    public {m.BackingTypeName} Value {{ get; set; }}");
        _ = sb.AppendLine();

        // ── Constructor ─────────────────────────────────────────────────────
        _ = sb.AppendLine($"    public {m.StructName}({m.BackingTypeName} value) => Value = value;");
        _ = sb.AppendLine();

        // ── Factory ─────────────────────────────────────────────────────────
        _ = sb.AppendLine($"    public static {m.StructName} NewId() => new({m.NewIdExpression});");
        _ = sb.AppendLine();

        // ── Empty / default ─────────────────────────────────────────────────
        _ = sb.AppendLine($"    public static readonly {m.StructName} Empty = default;");
        _ = sb.AppendLine();

        // ── Conversions ─────────────────────────────────────────────────────
        _ = sb.AppendLine($"    public static implicit operator {m.BackingTypeName}({m.StructName} id) => id.Value;");
        _ = sb.AppendLine($"    public static explicit operator {m.StructName}({m.BackingTypeName} value) => new(value);");
        _ = sb.AppendLine();

        // ── IComparable<T> ──────────────────────────────────────────────────
        _ = sb.AppendLine($"    public int CompareTo({m.StructName} other) => Value.CompareTo(other.Value);");
        _ = sb.AppendLine();

        // ── IParsable<T> ────────────────────────────────────────────────────
        EmitIParsable(sb, m);

        // ── ToString ────────────────────────────────────────────────────────
        _ = sb.AppendLine($"    public override string ToString() => Value.ToString()!;");
        _ = sb.AppendLine();

        // ── System.Text.Json converter ──────────────────────────────────────
        EmitJsonConverter(sb, m);

        // ── EF Core ValueConverter (conditional) ────────────────────────────
        if (m.EmitEfCoreConverter)
            EmitEfCoreConverter(sb, m);

        _ = sb.AppendLine("}");

        return sb.ToString();
    }

    // ────────────────────────────────────────────────────────────────────────
    //  IParsable<T>
    // ────────────────────────────────────────────────────────────────────────

    private static void EmitIParsable(StringBuilder sb, StronglyTypedIdModel m)
    {
        // Parse
        _ = sb.AppendLine($"    public static {m.StructName} Parse(string s, IFormatProvider? provider)");
        _ = sb.AppendLine("    {");

        if (m.BackingType == BackingType.String)
        {
            _ = sb.AppendLine($"        return new(s);");
        }
        else
        {
            var parseCall = m.BackingType == BackingType.Guid
                ? $"global::System.Guid.Parse(s)"
                : $"global::System.{(m.BackingType == BackingType.Int ? "Int32" : "Int64")}.Parse(s, provider)";
            _ = sb.AppendLine($"        return new({parseCall});");
        }

        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();

        // TryParse
        _ = sb.AppendLine($"    public static bool TryParse(string? s, IFormatProvider? provider, out {m.StructName} result)");
        _ = sb.AppendLine("    {");

        if (m.BackingType == BackingType.String)
        {
            _ = sb.AppendLine("        if (s is null) { result = default; return false; }");
            _ = sb.AppendLine("        result = new(s);");
            _ = sb.AppendLine("        return true;");
        }
        else if (m.BackingType == BackingType.Guid)
        {
            _ = sb.AppendLine("        if (global::System.Guid.TryParse(s, out var v)) { result = new(v); return true; }");
            _ = sb.AppendLine("        result = default;");
            _ = sb.AppendLine("        return false;");
        }
        else
        {
            var clrType = m.BackingType == BackingType.Int ? "int" : "long";
            _ = sb.AppendLine($"        if ({clrType}.TryParse(s, provider, out var v)) {{ result = new(v); return true; }}");
            _ = sb.AppendLine("        result = default;");
            _ = sb.AppendLine("        return false;");
        }

        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
    }

    // ────────────────────────────────────────────────────────────────────────
    //  System.Text.Json converter
    // ────────────────────────────────────────────────────────────────────────

    private static void EmitJsonConverter(StringBuilder sb, StronglyTypedIdModel m)
    {
        _ = sb.AppendLine($"    public sealed class {m.StructName}JsonConverter : JsonConverter<{m.StructName}>");
        _ = sb.AppendLine("    {");

        // Read
        _ = sb.AppendLine($"        public override {m.StructName} Read(ref Utf8JsonReader reader, global::System.Type typeToConvert, JsonSerializerOptions options)");
        _ = sb.AppendLine("        {");

        switch (m.BackingType)
        {
            case BackingType.Guid:
                _ = sb.AppendLine("            return new(reader.GetGuid());");
                break;
            case BackingType.Int:
                _ = sb.AppendLine("            return new(reader.GetInt32());");
                break;
            case BackingType.Long:
                _ = sb.AppendLine("            return new(reader.GetInt64());");
                break;
            case BackingType.String:
                _ = sb.AppendLine("            return new(reader.GetString()!);");
                break;
        }

        _ = sb.AppendLine("        }");
        _ = sb.AppendLine();

        // Write
        _ = sb.AppendLine($"        public override void Write(Utf8JsonWriter writer, {m.StructName} value, JsonSerializerOptions options)");
        _ = sb.AppendLine("        {");

        switch (m.BackingType)
        {
            case BackingType.Guid:
            case BackingType.String:
                _ = sb.AppendLine("            writer.WriteStringValue(value.Value.ToString());");
                break;
            case BackingType.Int:
                _ = sb.AppendLine("            writer.WriteNumberValue(value.Value);");
                break;
            case BackingType.Long:
                _ = sb.AppendLine("            writer.WriteNumberValue(value.Value);");
                break;
        }

        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
    }

    // ────────────────────────────────────────────────────────────────────────
    //  EF Core ValueConverter (only emitted when EF Core is referenced)
    // ────────────────────────────────────────────────────────────────────────

    private static void EmitEfCoreConverter(StringBuilder sb, StronglyTypedIdModel m)
    {
        _ = sb.AppendLine($"    public sealed class {m.StructName}ValueConverter");
        _ = sb.AppendLine($"        : global::Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter<{m.StructName}, {m.BackingTypeName}>");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine($"        public {m.StructName}ValueConverter()");
        _ = sb.AppendLine($"            : base(id => id.Value, value => new(value)) {{ }}");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
    }
}
