using Microsoft.CodeAnalysis;

namespace AStar.Dev.Source.Generators;

internal static class StrongIdCodeGenerator
{
    public static string Generate(StrongIdModel model)
    {
        var ns = model.Namespace is null ? string.Empty : $"namespace {model.Namespace};";
        var accessibility = AccessibilityToString(model.Accessibility);
        var underlying = GetRequiredUnderlyingIdType(model);

        var code = $$"""
             // <auto-generated/>

             using System;
             using System.Collections.Generic;

             {{(string.IsNullOrEmpty(ns) ? string.Empty : ns)}}

             {{accessibility}} readonly partial record struct {{model.Name}}({{underlying}} Id);

             """;

        return code;

        static string AccessibilityToString(Accessibility a)
            => a == Accessibility.Internal ? "internal" : "public";
    }

    private static string GetRequiredUnderlyingIdType(StrongIdModel model)
    {
        var underlying = model.UnderlyingTypeDisplay;
        if(string.IsNullOrEmpty(underlying))
            return "System.Guid";
        
        if(underlying.IndexOf('.') < 0)
        {
            if(underlying == "Guid")
                underlying = "System.Guid";
            else if(underlying == "string")
                underlying = "System.String";
            else if(underlying == "int")
                underlying = "System.Int32";
        }

        return underlying;
    }
}
