using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AStar.Dev.Source.Generators;

internal static class ServiceCollectionCodeGenerator
{
    public static string Generate(IReadOnlyList<ServiceRegistrationGenerator.ServiceModel> items)
    {
        IEnumerable<string> registrations = BuildServiceRegistrations(items);
        return BuildSourceFile(registrations);
    }

    private static IEnumerable<string> BuildServiceRegistrations(IReadOnlyList<ServiceRegistrationGenerator.ServiceModel> items)
    {
        var seen = new HashSet<string>(StringComparer.Ordinal);

        foreach(ServiceRegistrationGenerator.ServiceModel model in items)
        {
            foreach(var registration in CreateRegistrationsForModel(model).Where(seen.Add))
            {
                yield return registration;
            }
        }
    }

    private static IEnumerable<string> CreateRegistrationsForModel(ServiceRegistrationGenerator.ServiceModel model)
    {
        var method = GetRegistrationMethod(model.Lifetime);

        if(!string.IsNullOrEmpty(model.ServiceFqn))
        {
            yield return $"        s.{method}<{model.ServiceFqn}, {model.ImplFqn}>();";

            if(model.AlsoAsSelf)
                yield return $"        s.{method}<{model.ImplFqn}>();";
        }
        else
        {
            yield return $"        s.{method}<{model.ImplFqn}>();";
        }
    }

    private static string GetRegistrationMethod(ServiceRegistrationGenerator.Lifetime lifetime) => lifetime switch
    {
        ServiceRegistrationGenerator.Lifetime.Singleton => "AddSingleton",
        ServiceRegistrationGenerator.Lifetime.Scoped => "AddScoped",
        ServiceRegistrationGenerator.Lifetime.Transient => "AddTransient",
        _ => "AddScoped"
    };

    private static string BuildSourceFile(IEnumerable<string> registrations)
    {
        var sb = new StringBuilder();
        _ = sb.AppendLine("// <auto-generated/>");
        _ = sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        _ = sb.AppendLine();
        _ = sb.AppendLine("public static class GeneratedServiceCollectionExtensions");
        _ = sb.AppendLine("{");
        _ = sb.AppendLine("    public static IServiceCollection AddAnnotatedServices(this IServiceCollection s)");
        _ = sb.AppendLine("    {");

        foreach(var registration in registrations)
            _ = sb.AppendLine(registration);

        _ = sb.AppendLine("        return s;");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine("}");

        return sb.ToString();
    }
}
