using Microsoft.CodeAnalysis;

namespace AStar.Dev.Source.Generators;

internal static class StrongIdCodeGenerator
{
    private const string AutoGeneratedComment = "// <auto-generated/>";
    private const string Usings = "using System;\nusing System.Collections.Generic;";

    public static string Generate(StrongIdModel model)
    {
        var ns = model.Namespace is null ? string.Empty : $"namespace {model.Namespace};";
        var accessibility = model.Accessibility == Accessibility.Internal ? "internal" : "public";
        var underlying = GetRequiredUnderlyingIdType(model);

        // Use string interpolation for code generation
        return $"{AutoGeneratedComment}\n\n{Usings}\n\n{(string.IsNullOrEmpty(ns) ? string.Empty : ns)}\n\n{accessibility} readonly partial record struct {model.Name}({underlying} Id);\n";
    }

    private static string GetRequiredUnderlyingIdType(StrongIdModel model)
    {
        var underlying = model.UnderlyingTypeDisplay;
        if (string.IsNullOrEmpty(underlying))
            return "System.Guid";

        if (underlying.IndexOf('.') < 0)
        {
            if (underlying == "Guid")
                underlying = "System.Guid";
            else if (underlying == "string")
                underlying = "System.String";
            else if (underlying == "int")
                underlying = "System.Int32";
        }

        return underlying;
    }
}
